-- AlterTable
ALTER TABLE "GuestLink" ADD COLUMN "contact" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GuestLink" ADD COLUMN "notes" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GuestLink" ADD COLUMN "side" TEXT NOT NULL DEFAULT '';
